# Privilegios para `iw`@`%`

GRANT ALL PRIVILEGES ON *.* TO 'iw'@'%' IDENTIFIED BY PASSWORD '*66ECFB37033BF55F9A2B98BCE76941B80C74E161' WITH GRANT OPTION;

GRANT ALL PRIVILEGES ON `ebay`.* TO 'iw'@'%' WITH GRANT OPTION;

GRANT ALL PRIVILEGES ON `iw\_%`.* TO 'iw'@'%' WITH GRANT OPTION;
